function [performMotionCorrection, line_to_line_motion_correction ] = MC_gui_initial( )
%INITIALGUI Summary of this function goes here
%   Detailed explanation goes here
% Help goes here.

% Code running parameters
performMotionCorrection = true;
line_to_line_motion_correction = true;

guiHeight = 200;
guiWidth = 300;

%%% POSITION: [from-left from-bottom width height]

% 'position', all distance units in pixels: [xdist ydist width height]
S.fh = figure('units','pixels',...
            'position',[300 300 guiWidth guiHeight],...
         	'menubar','none',...
          	'name','Ca Code',...
         	'numbertitle','off',...
        	'resize','off');
S.title = uicontrol('Style','text','fontsize',16,...
            'fontweight','bold',...
            'String','Motion Correction Parameters',...
            'Position',[5 guiHeight-60 guiWidth 50]);
S.horozontalLine = uicontrol('Style','text','fontsize',12,...
            'fontweight','bold',...
            'String','',...
            'Position',[0 270 600 2],'backgroundcolor','k');
%%% Running Data Checkbox
S.checkbox1 = uicontrol('style','checkbox',...
          	'unit','pix',...
           	'position',[18 60 280 20],...
         	'fontsize',12,...
           	'fontweight','bold',... 
         	'callback',@checkbox1_Callback,...
          	'value',1);
S.checkboxText1 = uicontrol('Style','text','fontsize',12,...
            'fontweight','bold',...
            'String','< Perform motion correction.',...
            'Position',[35 40 210 40]);
        
S.checkbox2 = uicontrol('style','checkbox',...
          	'unit','pix',...
           	'position',[18 120 280 20],...
         	'fontsize',12,...
           	'fontweight','bold',... 
         	'callback',@checkbox2_Callback,...
          	'value',1);
S.checkboxText2 = uicontrol('Style','text','fontsize',12,...
            'fontweight','bold',...
            'String','< Use line to line alignment during motion correction.',...
            'Position',[35 100 210 40]);
%%% START Button
S.buttonStart = uicontrol('style','push',...
            'unit','pix',...
         	'position',[10 15 280 20],...
            'fontsize',12,...
            'fontweight','bold',... 
          	'string','START',...
           	'callback',@button_start_call);


guidata(S.fh,S)
movegui('center')

function [] = button_start_call(varargin)
    % Callback for pushbutton.
    S = guidata(gcbf);
    
    performMotionCorrection = get(S.checkbox1,'Value');
    line_to_line_motion_correction = get(S.checkbox2,'Value');
    
    close all force
end

function checkbox1_Callback(hObject, eventdata, handles)
% hObject    handle to checkbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of checkbox1
%   NOT USED, AL DONE IN ABOVE FUNCTION. LEFT FOR REFERENCE
end

function checkbox2_Callback(hObject, eventdata, handles)
% hObject    handle to checkbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of checkbox1
%   NOT USED, AL DONE IN ABOVE FUNCTION. LEFT FOR REFERENCE
end

%%% Pauses the program until the figure 'S.fh' closes
waitfor(S.fh)

end

